// main.js

// Import the WASM module and glue code generated by wasm-pack
import init, { predict } from "e:/testrust/barutest/pkg";

async function run() {
  // Initialize the WASM module
  await init();

  // Call the Rust function
  const heroLevel = 6.0;
  const deathTime = 221.0;
  const result = predict(heroLevel, deathTime);

  console.log(`Prediction: ${result}`);

  // Optional: benchmark
  const iterations = 1_000_000;
  const start = performance.now();
  for (let i = 0; i < iterations; i++) {
    predict(heroLevel, deathTime);
  }
  const duration = performance.now() - start;
  console.log(`Time for ${iterations} iterations: ${duration.toFixed(2)} ms`);
}

// Run the function
run();
